#!/bin/bash
# Install / uninstall launchd KeepAlive for omni-exp (experimental phone agent).
#
# Root causes of past silent deaths:
#  1) Agent/Cursor shells started omni in their process group → shell exit
#     SIGTERM'd the child (no Python traceback).
#  2) First launchd attempt pointed ProgramArguments/WorkingDirectory into
#     ~/Documents → macOS TCC "Operation not permitted" (exit 78 EX_CONFIG).
#
# Fix: launchd job runs a runner under
#   ~/Library/Application Support/Sutando/omni-exp/
# which is outside TCC-protected folders, with KeepAlive.
#
# Usage:
#   bash src/install-omni-exp-launchd.sh
#   bash src/install-omni-exp-launchd.sh --uninstall|--status|--restart
set -e

LABEL="com.sutando.omni-exp-agent"
REPO="$(cd "$(dirname "$0")/.." && pwd)"
TEMPLATE="$REPO/src/launchd/$LABEL.plist"
DEST="$HOME/Library/LaunchAgents/$LABEL.plist"
SUPPORT="$HOME/Library/Application Support/Sutando/omni-exp"
DOMAIN="gui/$(id -u)"
SERVICE="$DOMAIN/$LABEL"

__HELPER="$REPO/src/workspace_resolve.sh"
[ -f "$__HELPER" ] || __HELPER="$(cd "$(dirname "$0")" && pwd)/workspace_resolve.sh"
# shellcheck source=workspace_resolve.sh
source "$__HELPER"
resolve_workspace_or_die

resolve_brew_bin() {
  [ -d /opt/homebrew/bin ] && { echo /opt/homebrew/bin; return; }
  [ -d /usr/local/bin ] && { echo /usr/local/bin; return; }
  echo /usr/bin
}

bootout_if_loaded() {
  if launchctl print "$SERVICE" >/dev/null 2>&1; then
    echo "  Existing job found, removing first..."
    launchctl bootout "$SERVICE" 2>/dev/null || true
    for _ in $(seq 1 10); do
      launchctl print "$SERVICE" >/dev/null 2>&1 || break
      sleep 0.3
    done
  fi
}

materialize_runner() {
  mkdir -p "$SUPPORT"
  # Snapshot .env into Support — launchd cannot source ~/Documents/.env (TCC).
  if [ -f "$REPO/.env" ]; then
    cp "$REPO/.env" "$SUPPORT/env"
    chmod 600 "$SUPPORT/env"
  else
    : > "$SUPPORT/env"
  fi
  cat > "$SUPPORT/run-omni-exp.sh" <<EOF
#!/bin/bash
# Auto-generated by install-omni-exp-launchd.sh — do not edit.
# Repo checkout may live under ~/Documents (TCC); this runner does not.
set -u
REPO="$REPO"
SUPPORT="$SUPPORT"
cd /tmp || true
if [[ -f "\$SUPPORT/env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "\$SUPPORT/env" || true
  set +a
fi
PORT="\${OMNI_EXP_PORT:-\${OMNI_PORT:-7090}}"
PYTHON="\${OMNI_EXP_PYTHON:-\${OMNI_PYTHON:-\$REPO/.venv/bin/python}}"
if [[ ! -x "\$PYTHON" ]]; then
  PYTHON="\$(command -v python3 || true)"
fi
if [[ -z "\${PYTHON:-}" || ! -x "\$PYTHON" ]]; then
  echo "omni-launchd: no python" >&2
  exit 1
fi
CERT="\$REPO/state/server.crt"
KEY="\$REPO/state/server.key"
if [[ ! -f "\$CERT" || ! -f "\$KEY" ]]; then
  mkdir -p "\$REPO/state"
  /usr/bin/openssl req -x509 -newkey rsa:2048 -keyout "\$KEY" -out "\$CERT" \\
    -days 365 -nodes -subj "/CN=sutando-local" 2>/dev/null || true
fi
# Evict stale non-launchd listeners
if command -v lsof >/dev/null 2>&1; then
  stale=\$(lsof -nP -iTCP:"\$PORT" -sTCP:LISTEN -t 2>/dev/null || true)
  if [[ -n "\${stale:-}" ]]; then
    kill \$stale 2>/dev/null || true
    sleep 0.4
    kill -9 \$stale 2>/dev/null || true
  fi
fi
exec "\$PYTHON" -u "\$REPO/src/omni-exp-agent.py"
EOF
  chmod +x "$SUPPORT/run-omni-exp.sh"
  # Convenience symlink into workspace logs when possible
  mkdir -p "$WORKSPACE/logs"
  ln -sfn "$SUPPORT/omni-exp-agent.log" "$WORKSPACE/logs/omni-exp-agent.launchd.log" 2>/dev/null || true
}

cmd="${1:-install}"
case "$cmd" in
  install)
    [ -f "$TEMPLATE" ] || { echo "ERROR: missing $TEMPLATE" >&2; exit 1; }
    [ -f "$REPO/src/omni-exp-agent.py" ] || { echo "ERROR: missing omni-exp-agent.py" >&2; exit 1; }
    BREW_BIN="$(resolve_brew_bin)"
    echo "Installing $LABEL"
    echo "  repo:     $REPO"
    echo "  support:  $SUPPORT"
    echo "  (runner lives outside ~/Documents to satisfy macOS TCC)"
    mkdir -p "$HOME/Library/LaunchAgents"
    pkill -f "$REPO/src/omni-exp-agent.py" 2>/dev/null || true
    pkill -f "$REPO/src/omni-agent.py" 2>/dev/null || true
    # Legacy label before omni-exp rename
    launchctl bootout "$DOMAIN/com.sutando.omni-agent" 2>/dev/null || true
    rm -f "$HOME/Library/LaunchAgents/com.sutando.omni-agent.plist"
    pkill -f "$REPO/src/omni-exp-supervisor.sh" 2>/dev/null || true
    # Clear test labels if present
    launchctl bootout "$DOMAIN/com.sutando.omni-test4" 2>/dev/null || true
    sleep 0.4
    materialize_runner
    sed \
      -e "s|__SUPPORT__|$SUPPORT|g" \
      -e "s|__BREW_BIN__|$BREW_BIN|g" \
      -e "s|__HOME__|$HOME|g" \
      "$TEMPLATE" > "$DEST"
    bootout_if_loaded
    launchctl bootstrap "$DOMAIN" "$DEST"
    echo "  Loaded via $SERVICE"
    for _ in $(seq 1 25); do
      lsof -nP -iTCP:"${OMNI_EXP_PORT:-${OMNI_PORT:-7090}}" -sTCP:LISTEN >/dev/null 2>&1 && break
      sleep 0.25
    done
    if lsof -nP -iTCP:"${OMNI_EXP_PORT:-${OMNI_PORT:-7090}}" -sTCP:LISTEN >/dev/null 2>&1; then
      echo "  ✓ listening on ${OMNI_EXP_PORT:-${OMNI_PORT:-7090}}"
    else
      echo "  ⚠ not listening — check $SUPPORT/omni-exp-agent.log" >&2
    fi
    echo
    echo "omni-exp is launchd-managed (KeepAlive)."
    echo "  After editing repo .env: re-run this install (copies env → Support)."
    echo "  URL: https://127.0.0.1:${OMNI_EXP_PORT:-${OMNI_EXP_PORT:-${OMNI_PORT:-7090}}}/omni-exp"
    ;;
  --uninstall|uninstall)
    bootout_if_loaded
    rm -f "$DEST"
    echo "Uninstalled $LABEL (left $SUPPORT in place)"
    ;;
  --status|status)
    echo "Service: $SERVICE"
    if launchctl print "$SERVICE" >/dev/null 2>&1; then
      launchctl print "$SERVICE" | grep -E '^\s+(state|pid|last exit code|runs|path)' || true
    else
      echo "  (not loaded)"
    fi
    if lsof -nP -iTCP:"${OMNI_EXP_PORT:-${OMNI_PORT:-7090}}" -sTCP:LISTEN >/dev/null 2>&1; then
      echo "  port ${OMNI_EXP_PORT:-${OMNI_PORT:-7090}}: LISTEN"
    else
      echo "  port ${OMNI_EXP_PORT:-${OMNI_PORT:-7090}}: down"
    fi
    echo "  log: $SUPPORT/omni-exp-agent.log"
    ;;
  --restart|restart)
    if ! launchctl print "$SERVICE" >/dev/null 2>&1; then
      exec bash "$0" install
    fi
    # Refresh env snapshot on restart
    materialize_runner
    launchctl kickstart -k "$SERVICE"
    for _ in $(seq 1 25); do
      lsof -nP -iTCP:"${OMNI_EXP_PORT:-${OMNI_PORT:-7090}}" -sTCP:LISTEN >/dev/null 2>&1 && break
      sleep 0.25
    done
    bash "$0" --status
    ;;
  *)
    echo "Usage: $0 [install|--uninstall|--status|--restart]" >&2
    exit 2
    ;;
esac
